// AUTO-GENERATED by scripts/measure-frames.mjs — do not edit by hand.
// Regenerated on every dev/build run from public/sequence/frame-01.webp.

export type FrameDimensions = Readonly<{ width: number; height: number }>;

export const frameDimensions: FrameDimensions = { width: 720, height: 1280 };

/** 720×1280 → 0.563:1 (portrait). */
export const frameAspectRatio = 0.562500;

/**
 * Average colour of the frame corners. The stage is painted this so a
 * "contain" frame blends into the page instead of showing a hard edge.
 */
export const frameBackground = "#060508";
