// AUTO-GENERATED by scripts/detect-logo.mjs — do not edit by hand.
// Regenerated on every `npm run dev` and `npm run build`.

export type DetectedLogo = {
  src: string;
  width: number;
  height: number;
  /** "circle" when the source is opaque, so background corners are hidden. */
  mask: "circle" | "none";
};

export const detectedLogo: DetectedLogo | null = {
  src: "/images/logo.png",
  width: 560,
  height: 554,
  mask: "none",
};
