/**
 * Generates supabase/seed.sql from the existing hardcoded data files.
 *
 *   npm run seed:generate
 *
 * The menu was transcribed by hand from the official Canva menu and verified
 * against the rendered page. Re-typing 92 items into SQL would be a second
 * chance to introduce a typo into someone's prices, so the seed is generated
 * from `data/menu.ts` instead — one source of truth, mechanically converted.
 *
 * Prices are stored as integers in Rwandan francs. The display strings
 * ("6,000 RWF") are parsed here rather than in the app, so the database holds
 * a number that can be sorted, summed and edited in a form field.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

const OUT = path.join(process.cwd(), "supabase", "seed.sql");

/** SQL string literal, or NULL. */
function q(value) {
  if (value === null || value === undefined || value === "") return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** SQL jsonb literal. */
function j(value) {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

/** text[] literal. */
function arr(values) {
  if (!values || values.length === 0) return "'{}'";
  return `array[${values.map((v) => q(v)).join(", ")}]`;
}

/**
 * "6,000 RWF" -> 6000. Returns null for null/undefined/unparseable.
 * Throws on anything that looks like a price but isn't cleanly numeric, so a
 * malformed entry fails the build instead of silently seeding a wrong number.
 */
function priceToInt(value) {
  if (value === null || value === undefined) return null;
  const digits = String(value).replace(/[^\d]/g, "");
  if (digits === "") {
    throw new Error(`Cannot parse a price from ${JSON.stringify(value)}`);
  }
  return Number.parseInt(digits, 10);
}

async function main() {
  const { menu } = await import("../data/menu.ts");
  const { restaurant } = await import("../data/restaurant.ts");

  const lines = [];
  const push = (s = "") => lines.push(s);

  push("-- =============================================================================");
  push("-- Traveling Roots — seed data");
  push("-- =============================================================================");
  push("-- AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.");
  push("-- Regenerate with: npm run seed:generate");
  push("--");
  push("-- Everything here is verified business information or the real menu as");
  push("-- transcribed from the official Canva menu. Nothing is invented.");
  push("--");
  push("-- Safe to re-run: every statement is idempotent.");
  push("-- =============================================================================");
  push();
  push("begin;");
  push();

  /* ---------------- site_settings ---------------- */

  push("-- ---------------------------------------------------------------- settings");
  push(`insert into public.site_settings (id, site_title, meta_description, canonical_url)`);
  push(
    `values (1, ${q("Traveling Roots | Restaurant in Musanze, Rwanda")}, ` +
      `${q("Garden restaurant in Musanze, Rwanda. Globally inspired, sustainably grown food from our own chef's garden. Open daily 12:00–22:00.")}, ` +
      `${q(restaurant.website)})`,
  );
  push("on conflict (id) do nothing;");
  push();

  /* ---------------- business_info ---------------- */

  const hours = restaurant.hours.flatMap((block) =>
    block.schemaDays.map((day) => ({ day, opens: block.opens, closes: block.closes })),
  );

  push("-- ------------------------------------------------------------- business");
  push(
    "insert into public.business_info (id, name, legal_name, tagline, street, city, country, " +
      "plus_code, phone, whatsapp, email, directions_url, website, opening_hours)",
  );
  push(
    `values (1, ${q(restaurant.name)}, ${q(restaurant.legalName)}, ${q(restaurant.tagline)}, ` +
      `${q(restaurant.streetAddress)}, ${q(restaurant.city)}, ${q(restaurant.country)}, ` +
      `${q(restaurant.plusCode)}, ${q(restaurant.phone.e164)}, ${q(restaurant.whatsapp.e164)}, ` +
      `${q(restaurant.email)}, ${q(restaurant.directionsUrl)}, ${q(restaurant.website)}, ${j(hours)})`,
  );
  push("on conflict (id) do nothing;");
  push();

  /* ---------------- hero_media ---------------- */

  push("-- ------------------------------------------------------------ hero media");
  push("-- Created inactive and with no video: the owner uploads one from");
  push("-- /admin/dashboard/hero. Until then the site falls back to the still hero.");
  push("-- title/subtitle stay NULL so the component uses the designed hero copy in");
  push("-- data/site.ts; the database only overrides it when the owner types something.");
  push(
    "insert into public.hero_media (is_active) " +
      "select false where not exists (select 1 from public.hero_media);",
  );
  push();

  /* ---------------- social links ---------------- */

  push("-- ---------------------------------------------------------- social links");
  restaurant.socials.forEach((social, index) => {
    push(
      "insert into public.social_links (platform, label, url, sort_order) " +
        `select ${q(social.platform ?? social.label)}, ${q(social.label)}, ${q(social.href)}, ${index} ` +
        `where not exists (select 1 from public.social_links where url = ${q(social.href)});`,
    );
  });
  push();

  /* ---------------- menu ---------------- */

  push("-- ------------------------------------------------------------------ menu");
  push("-- 11 categories, " + menu.reduce((n, c) => n + c.sections.length, 0) + " sections, " +
    menu.reduce((n, c) => n + c.sections.reduce((m, s) => m + s.items.length, 0), 0) + " items.");
  push();

  let categoryIndex = 0;
  for (const category of menu) {
    push(`-- ${category.category}`);
    push(
      "insert into public.menu_categories (slug, name, intro, sort_order) " +
        `values (${q(category.id)}, ${q(category.category)}, ${q(category.intro ?? null)}, ${categoryIndex}) ` +
        "on conflict (slug) do nothing;",
    );

    let sectionIndex = 0;
    for (const section of category.sections) {
      // Sections have no natural key, so guard on (category, title) —
      // NULL title needs `is not distinct from`, since NULL = NULL is unknown.
      push(
        "insert into public.menu_sections (category_id, title, note, sort_order) " +
          `select c.id, ${q(section.title ?? null)}, ${q(section.note ?? null)}, ${sectionIndex} ` +
          `from public.menu_categories c where c.slug = ${q(category.id)} ` +
          "and not exists (select 1 from public.menu_sections s " +
          `where s.category_id = c.id and s.title is not distinct from ${q(section.title ?? null)});`,
      );

      let itemIndex = 0;
      for (const item of section.items) {
        const variants = (item.variants ?? []).map((v) => ({
          label: v.label,
          price: priceToInt(v.price),
        }));

        push(
          "insert into public.menu_items " +
            "(section_id, name, description, price, dietary, variants, availability_note, sort_order) " +
            `select s.id, ${q(item.name)}, ${q(item.description ?? null)}, ` +
            `${priceToInt(item.price) ?? "null"}, ${arr(item.dietary)}, ${j(variants)}, ` +
            `${q(item.availability ?? null)}, ${itemIndex} ` +
            "from public.menu_sections s join public.menu_categories c on c.id = s.category_id " +
            `where c.slug = ${q(category.id)} and s.title is not distinct from ${q(section.title ?? null)} ` +
            `and not exists (select 1 from public.menu_items i where i.section_id = s.id and i.name = ${q(item.name)});`,
        );
        itemIndex += 1;
      }
      sectionIndex += 1;
    }
    push();
    categoryIndex += 1;
  }

  push("commit;");
  push();

  await writeFile(OUT, lines.join("\n"), "utf8");

  const items = menu.reduce(
    (n, c) => n + c.sections.reduce((m, s) => m + s.items.length, 0),
    0,
  );
  console.log(
    `Wrote supabase/seed.sql — ${menu.length} categories, ` +
      `${menu.reduce((n, c) => n + c.sections.length, 0)} sections, ${items} items, ` +
      `${restaurant.socials.length} social links.`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
