/**
 * Measures the real frame dimensions and writes them into the app.
 *
 * Runs automatically on `predev` / `prebuild`, so swapping the sequence for a
 * different aspect ratio needs no code edits — the layout follows the frames.
 *
 * Knowing the size at build time means the server renders the correct
 * composition on the first paint, instead of guessing and then re-laying-out
 * once the first frame decodes in the browser.
 */

import { writeFile, access } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const FIRST_FRAME = path.join(process.cwd(), "public", "sequence", "frame-01.webp");
const OUT = path.join(process.cwd(), "data", "frames.generated.ts");

const header = `// AUTO-GENERATED by scripts/measure-frames.mjs — do not edit by hand.
// Regenerated on every dev/build run from public/sequence/frame-01.webp.

export type FrameDimensions = Readonly<{ width: number; height: number }>;

`;

/**
 * Average colour of the four frame corners.
 *
 * The stage behind the canvas is painted this colour so a "contain" frame
 * blends into the page instead of reading as a hard-edged rectangle sitting
 * on a different background.
 *
 * Measured from an explicit raw buffer: sharp's `.stats()` is computed on the
 * input image and ignores `.extract()`, which would silently return the
 * whole-image mean instead of the corner.
 */
async function cornerColour(file, width, height) {
  const patch = Math.max(8, Math.round(Math.min(width, height) * 0.05));
  const corners = [
    { left: 0, top: 0 },
    { left: width - patch, top: 0 },
    { left: 0, top: height - patch },
    { left: width - patch, top: height - patch },
  ];

  let r = 0;
  let g = 0;
  let b = 0;

  for (const corner of corners) {
    const buffer = await sharp(file)
      .extract({ ...corner, width: patch, height: patch })
      .flatten({ background: { r: 0, g: 0, b: 0 } })
      .raw()
      .toBuffer();
    let cr = 0;
    let cg = 0;
    let cb = 0;
    for (let i = 0; i < buffer.length; i += 3) {
      cr += buffer[i];
      cg += buffer[i + 1];
      cb += buffer[i + 2];
    }
    const pixels = buffer.length / 3;
    r += cr / pixels;
    g += cg / pixels;
    b += cb / pixels;
  }

  const hex = (value) => Math.round(value / 4).toString(16).padStart(2, "0");
  return `#${hex(r)}${hex(g)}${hex(b)}`;
}

async function main() {
  let width = 1600;
  let height = 1000;
  let background = "#0e1a13";
  let found = false;

  try {
    await access(FIRST_FRAME);
    const meta = await sharp(FIRST_FRAME).metadata();
    if (meta.width && meta.height) {
      width = meta.width;
      height = meta.height;
      background = await cornerColour(FIRST_FRAME, width, height);
      found = true;
    }
  } catch {
    // No frames yet — fall through to the documented default.
  }

  const ratio = width / height;
  const orientation = ratio < 0.95 ? "portrait" : "landscape";

  const body =
    `export const frameDimensions: FrameDimensions = { width: ${width}, height: ${height} };\n` +
    `\n/** ${width}\u00d7${height} \u2192 ${ratio.toFixed(3)}:1 (${orientation}). */\n` +
    `export const frameAspectRatio = ${ratio.toFixed(6)};\n` +
    `\n/**\n * Average colour of the frame corners. The stage is painted this so a\n` +
    ` * "contain" frame blends into the page instead of showing a hard edge.\n */\n` +
    `export const frameBackground = "${background}";\n`;

  await writeFile(OUT, header + body, "utf8");

  console.log(
    found
      ? `Frames measured: ${width}\u00d7${height} (${orientation}), backdrop ${background}.`
      : `No frames found — data/frames.generated.ts written with the ${width}\u00d7${height} default.`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
