/**
 * Measures the real frame dimensions and writes them into the app.
 *
 * Runs automatically on `predev` / `prebuild`, so swapping the sequence for a
 * different aspect ratio needs no code edits — the layout follows the frames.
 *
 * Knowing the size at build time means the server renders the correct
 * composition on the first paint, instead of guessing and then re-laying-out
 * once the first frame decodes in the browser.
 */

import { writeFile, access } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const FIRST_FRAME = path.join(process.cwd(), "public", "sequence", "frame-01.webp");
const OUT = path.join(process.cwd(), "data", "frames.generated.ts");

const header = `// AUTO-GENERATED by scripts/measure-frames.mjs — do not edit by hand.
// Regenerated on every dev/build run from public/sequence/frame-01.webp.

export type FrameDimensions = Readonly<{ width: number; height: number }>;

`;

async function main() {
  let width = 1600;
  let height = 1000;
  let found = false;

  try {
    await access(FIRST_FRAME);
    const meta = await sharp(FIRST_FRAME).metadata();
    if (meta.width && meta.height) {
      width = meta.width;
      height = meta.height;
      found = true;
    }
  } catch {
    // No frames yet — fall through to the documented default.
  }

  const ratio = width / height;
  const orientation = ratio < 0.95 ? "portrait" : "landscape";

  const body =
    `export const frameDimensions: FrameDimensions = { width: ${width}, height: ${height} };\n` +
    `\n/** ${width}\u00d7${height} \u2192 ${ratio.toFixed(3)}:1 (${orientation}). */\n` +
    `export const frameAspectRatio = ${ratio.toFixed(6)};\n`;

  await writeFile(OUT, header + body, "utf8");

  console.log(
    found
      ? `Frames measured: ${width}\u00d7${height} (${orientation}).`
      : `No frames found — data/frames.generated.ts written with the ${width}\u00d7${height} default.`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
