import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import '../styles.css';

const maps='https://www.google.com/maps/dir/?api=1&destination=FJVH%2BXX%20Musanze';
const phone='tel:+250794317286';
const services=[['01','Special food nights','Gather around something different.'],['02',"Little chef's club",'Curiosity belongs in every kitchen.'],['03','Private events','Make the table your own.'],['04','Sustainable food experiences','A closer connection to what we eat.']];
function Logo(){return <a className="logo" href="#top" aria-label="Traveling Roots"><span className="logo-orbit">↗</span><span>TRAVELING<br/><i>ROOTS</i></span></a>}
function Parallax({className,children,depth='.1'}){return <div className={className} data-depth={depth}>{children}</div>}
function App(){
 const [tab,setTab]=useState('all');
 useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const els=document.querySelectorAll('[data-depth]');if(reduced)return;let ticking=false;const run=()=>{const y=scrollY;els.forEach(el=>el.style.transform=`translate3d(0,${Math.min(y*Number(el.dataset.depth),75)}px,0)`);ticking=false};const onScroll=()=>{if(!ticking){requestAnimationFrame(run);ticking=true}};addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[]);
 return <><header className="top"><Logo/><nav><a href="#journey">Our journey</a><a href="#menu">Menu</a><a href="#visit">Visit</a></nav><a className="top-call" href={phone}>0794 317 286 <b>↗</b></a></header><main id="top">
 <section className="hero"><div className="soil-art" aria-hidden="true"><div className="sun"/><div className="root r1"/><div className="root r2"/><div className="root r3"/><div className="seed">✦</div><i className="dust d1"/><i className="dust d2"/><i className="dust d3"/></div><div className="hero-noise"/><div className="hero-copy"><p className="kicker">Musanze · Rwanda <span>EST. AT THE TABLE</span></p><h1>Food with roots.<br/><em>Flavours without<br className="mobile"/> borders.</em></h1><p>A journey of sustainable ingredients, global flavours and unforgettable experiences.</p><div className="hero-actions"><a className="btn btn-terra" href="#journey">Explore our story <span>↓</span></a><a className="btn btn-line" href="#menu">View the menu <span>↗</span></a></div></div><div className="hero-edge"><span>01 / 06</span><span>Scroll to grow ↓</span></div></section>
 <section className="chapter garden" id="journey"><div className="chapter-index">02 <span>GARDEN</span></div><div className="leaf-art" aria-hidden="true"><div className="stem"/><div className="leaf l1"/><div className="leaf l2"/><div className="leaf l3"/><div className="leaf l4"/></div><div className="chapter-copy"><p className="kicker">The garden</p><h2>Where every<br/><em>journey begins.</em></h2><p>Our food begins with care for ingredients, creativity and the world around us. The journey starts close to the ground, then travels far.</p><span className="rule"/><p className="micro">ROOTS → GARDEN → INGREDIENTS</p></div></section>
 <section className="chapter kitchen"><div className="chapter-index">03 <span>KITCHEN</span></div><Parallax className="kitchen-photo photo" depth=".12"><img src="/hero-musanze.jpg" alt="Warm, atmospheric light at Traveling Roots"/></Parallax><div className="chapter-copy"><p className="kicker">From ingredient to flavour</p><h2>Crafted with<br/><em>purpose.</em></h2><p>From fresh ingredients to bold flavours, every dish has a story. Follow the good things as they move from garden to kitchen to plate.</p><div className="ingredient-list"><span>fresh</span><span>curious</span><span>shared</span></div></div></section>
 <section className="table-section"><Parallax className="table-image photo" depth=".08"><img src="/hero-musanze.jpg" alt="A warm dining space in Musanze"/></Parallax><div className="table-copy"><p className="kicker">04 · The table</p><h2>More than<br/><em>a meal.</em></h2><p>Come for the flavours. Stay for the experience.</p><div className="hero-actions"><a className="btn btn-terra" href={phone}>Reserve a table <span>↗</span></a><a className="text-link" href="#menu">Explore the menu <span>↓</span></a></div></div></section>
 <section className="experiences"><div className="chapter-index">05 <span>COMMUNITY</span></div><div className="section-heading"><p className="kicker">Make a little room</p><h2>More ways<br/><em>to gather.</em></h2><p>Traveling Roots is made for people, shared moments and experiences that stay with you.</p></div><div className="experience-grid">{services.map(([n,title,desc])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p><b>↗</b></article>)}</div></section>
 <section className="menu-section" id="menu"><div className="chapter-index">06 <span>THE MENU</span></div><div className="section-heading"><p className="kicker">On the table</p><h2>Good things,<br/><em>served simply.</em></h2><p>Our menu changes with the moment. Ask our team what is being served today.</p></div><div className="tabs">{['all','food','drinks','vegan'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x==='all'?'All':x==='vegan'?'Vegan friendly':x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="menu-note"><div className="bowl">◡</div><div><h3>{tab==='vegan'?'Ask about vegan-friendly options.':'Today’s menu is best discovered here.'}</h3><p>For current dishes, dietary options and prices, please speak with our team when you arrive.</p></div><a href={phone} className="text-link">Call ahead <span>↗</span></a></div></section>
 <section className="people"><div className="people-photo photo"><img src="/hero-musanze.jpg" alt="Traveling Roots restaurant atmosphere"/></div><div className="people-copy"><p className="kicker">The people</p><h2>Made<br/><em>for people.</em></h2><p>There’s a particular kind of magic in a place that makes room for everyone. Come as you are. Stay as long as you like.</p><p className="quote">“This was probably one of the best meals we've had in Africa”</p><small>— Mad or Nomad · Google review</small></div></section>
 <section className="visit" id="visit"><div className="visit-inner"><div><p className="kicker light">Come by</p><h2>Find your<br/><em>way here.</em></h2><a className="btn btn-light" href={maps} target="_blank" rel="noreferrer">Get directions <span>↗</span></a></div><div className="visit-details"><div><label>Location</label><a href={maps} target="_blank" rel="noreferrer">FJVH+XX Musanze<br/>Rwanda ↗</a></div><div><label>Hours</label><p>Open · closes 10 PM</p></div><div><label>Contact</label><a href={phone}>0794 317 286</a></div><div><label>Good to know</label><p>Dine-in · Takeaway<br/>No-contact delivery</p></div></div></div></section></main><footer><Logo/><div><p>Food with roots. Flavours without borders.</p><small>© 2026 Traveling Roots Ltd · Musanze, Rwanda</small></div><a href={phone} className="footer-link">Reserve / contact ↗</a></footer></>}

createRoot(document.getElementById('root')).render(<App/>);
